### ISSUE TITLE
[Q] Access to Storage of All Websites.

### ISSUE THREAD

**Issue by alpgul** [steampunck/swoosh-storage-specialist#1]
In chrome extension, I can access the cookies of all sites. but I can't access local storage and session storage. Is there a method to access this information of all websites without the websites being open?

**Comment by AndreLion** [comment]
Short answer: no.

This extension is supposed to access: 
- local storage and session storage in current origin.
- cookies in current origin and its top level domain. e.g `sub.domain.com` (current) and `.domain.com`

> In chrome extension, I can access the cookies of all sites.

Sounds like it's a bug. This extension _could_ access other sites' cookie (thanks to [Chrome extension API](https://developer.chrome.com/extensions/cookies)) but _should not_ display them according to the design.  I will investigate.

> Is there a method to access this information of all websites without the websites being open?

Unfortunately no. Due to web storage same origin restriction and lack of Chrome extension API. It's not possible at this moment.

**Comment by alpgul** [comment]
> In chrome extension, I can access the cookies of all sites.

`chrome.cookies.getAll( {}, function ( cookies ) {
})`

` "permissions": [
    "cookies",
    "<all_urls>"
  ]`
When I run this code, I can access the cookie data of the sites.
